# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1dc22a9add867e7f9882f8815b4bb80b72fad9c7fa902071d4e13ca8da5b1b3f1ecdb43dbf99420a7018f158b0403ae8dfec438e4b4df915c1a178459241c89

test:
  secret_key_base: 24e86b28d6b8166bc7aac47d3ad09a2a48eb1fdef2c659667ce6102a864e3903e961fe706bdaad50771c49176be53ee4e19c2b9a14dd14d488d714b4af460850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
